### ISSUE TITLE
comparing two images

### ISSUE THREAD

**Issue by nikky4D** [yabinzhangJohn/IRQA_Measure#1]
Is there an example showing how to compare two images? not a dataset like retargetme?

**Comment by yabinzhangJohn** [comment]
If you mean the MLF, since we use rankSVM to fuse features, you can train the fusion model on the entire retargetme instead of using LOOCV, and use the obtained model to predict the scores of two new images.

**Comment by nikky4D** [comment]
Thank you. Would you have an example I could follow?

**Comment by yabinzhangJohn** [comment]
You need to extract the functions from the for-loops in files such as [MLF_stage1_backwardregistration.m](https://github.com/yabinzhangJohn/IRQA_Measure/blob/master/MLF_code/MLF_stage1_backwardregistration.m) and [MLF_stage2_feat_egs.m](https://github.com/yabinzhangJohn/IRQA_Measure/blob/master/MLF_code/MLF_stage2_feat_egs.m).

**Comment by nikky4D** [comment]
Thank you. I will try that.

**Comment by tyalie** [comment]
Hi any luck, doing it?
